const { Event } = require('../models');

const eventData = [
    {
        modalId: 101,
        title: 'Brush Direwolves',
        notes: '',
        start: '2022-02-09',
        end: '2022-02-09',
        allDay: false,
        startTime: '18:00',
        endTime: '21:00',
        location: 'The Barn', 
        eventType: 'Required', 
        approval: true,
        familyName: 'Stark',
    },
    {
        modalId: 102,
        title: 'Sansa - Embriodery Class',
        notes: 'Poking things in a different way',
        start: '2022-02-19',
        end: '2022-02-19',
        allDay: false,
        startTime: '18:00',
        endTime: '21:00',
        location: '', 
        eventType: 'Required', 
        approval: true,
        familyName: 'Stark',
    },
    {
        modalId: 103,
        title: 'Show Arya how to stick them with the pointy end',
        notes: 'Poking things in the more fun way',
        start: '2022-02-20',
        end: '2022-02-20',
        allDay: true,
        startTime: '',
        endTime: '',
        location: 'The Barn', 
        eventType: 'Request', 
        approval: false,
        familyName: 'Stark',
    },
    {
        modalId: 104,
        title: 'Bran: See The Future',
        notes: '',
        start: '2022-02-21',
        end: '2022-02-21',
        allDay: false,
        startTime: '09:00',
        endTime: '10:00',
        location: 'Everywhere', 
        eventType: 'Optional', 
        approval: true,
        familyName: 'Stark',
    },
    {
        modalId: 105,
        title: 'Winter is Coming',
        notes: 'Everything is fine.',
        start: '2022-02-28',
        end: '2022-05-15',
        allDay: true,
        startTime: '',
        endTime: '',
        location: '', 
        eventType: 'Required', 
        approval: true,
        familyName: 'Stark',
    },
    {
        modalId: 106,
        title: 'Pay Debts',
        notes: '',
        start: '2022-02-21',
        end: '2022-02-21',
        allDay: false,
        startTime: '09:00',
        endTime: '10:00',
        location: 'Everywhere', 
        eventType: 'Required', 
        approval: true,
        familyName: 'Lannister',
    },
    {
        modalId: 107,
        title: 'Attend Court',
        notes: '',
        start: '2022-02-01',
        end: '2022-02-13',
        allDay: true,
        startTime: '',
        endTime: '',
        location: '', 
        eventType: 'Request', 
        approval: false,
        familyName: 'Lannister',
    },
    {
        modalId: 108,
        title: 'Joffrey: Torture People',
        notes: '',
        start: '2022-02-18',
        end: '2022-02-18',
        allDay: true,
        startTime: '17:00',
        endTime: '21:00',
        location: 'Throne Room', 
        eventType: 'Required', 
        approval: true,
        familyName: 'Lannister',
    },
    {
        modalId: 109,
        title: 'Tommen: cri over Margaery Tyrell',
        notes: '',
        start: '2022-02-19',
        end: '2022-02-19',
        allDay: true,
        startTime: '05:00',
        endTime: '17:00',
        location: 'Throne Room', 
        eventType: 'Optional', 
        approval: true,
        familyName: 'Lannister',
    },
];

const seedEvents = () => Event.bulkCreate(eventData);

module.exports = seedEvents;